### ISSUE TITLE
Allow the smart assistant to set the color temperature to a specific value

### ISSUE THREAD

**Issue by weiznich** [WebThingsIO/gateway#1576]
Currently it seems to only increase or decrease the color temperature by using a command like `make <light> warmer/cooler`. I've found no to increase/decrease the color temperature by a fixed value or set it to a fixed value. I've tried things like `make <light> warmer/cooler by 2000K`, `set color temperature to 5000K`.

**Comment by benfrancis** [comment]
Hi Weiznich,

This is intentional. I don't think "set color temperature to 5000K" is something that most users would understand. Similarly, we don't support commands like "Set the colour of the kitchen light to to #ff0000", but we do support "Set the colour of the kitchen light to red" instead (supporting the same set of pre-defined of colours that CSS supports).

Unfortunately there isn't really an equivalent human-friendly description of colour temperatures that I can think of, except maybe the very coarse "warm" and "cold".

**Comment by dhylands** [comment]
There are a few typical color temperatures that you see bulbs sold in: Warm White (or Soft White) (2000-3000K), Cool White (or Bright White) (3100-4500K), and Daylight (4600-6500K)

**Comment by dhylands** [comment]
https://www.standardpro.com/colour-temperature/

**Comment by weiznich** [comment]
@benfrancis I think I should clarify a bit what is exactly my issue.
Using `Make <light> warmer/cooler` works fine in that way that it changes the color temperature, but that does not mean that the change is visible. Looking at the values it seems that the color temperature is only changed by 100K. To archive a notable change one has to use command multiple times. 

I see multiple ways to improve that:
* Change the value used to adjust the color temperature to something bigger
* Use fixed values as proposed by @dhylands 
* Allow setting fixed numeric values (Yes not all users will know that, but those are the values that are visible if you look into the thing description. Also it does not mean everyone needs to use those commands if they are available, right?)

**Comment by benfrancis** [comment]
Interesting, I like the idea of using names like "warm white". Might be tricky to remember what the available options are though.

**Comment by flatsiedatsie** [comment]
One way is to let the users query the current color temperature. For example, if they like the current temperature, they would learn what it's called and in future set it to that level directly.
