### ISSUE TITLE
Gateway fails to start without local network

### ISSUE THREAD

**Issue by tim-hellhake** [WebThingsIO/gateway#2006]
If no lan or wlan is connected the gateway fails to start:
![image](https://user-images.githubusercontent.com/17127122/61009361-b9c7f780-a372-11e9-89d7-a16f72089f37.png)

**Comment by flatsiedatsie** [comment]
Ooh, thanks for spotting this! This will be pretty important in my use case.

**Comment by mrstegeman** [comment]
Not that this isn't an issue, but isn't the gateway pretty useless with no network connection?

**Comment by flatsiedatsie** [comment]
Although I can only speak for myself, I don't feel it's useless at all. 

In my case, once setup, the system can be controlled via voice and touch screen just fine.

In fact I'd argue that connecting to the network should not be the default. In my opinion, having a smart home system that connects to the network/internet as little as possible should be strived for. With each new scandal it becomes more obvious that IP technology has too many downsides. People will inevitably connect devices to their home wifi network (instead of creating a separate virtual network), and that's just a hack/leak/security fail waiting to happen. That's on top of the broader issue that WiFi devices can connect to the internet autonomously, sending personal data to the cloud without offering the consumer control.

I only purchases devices that create their own separate network (zigbee, z-wave, bluetooth, mysensors). IKEA understands this too. In the coming years this group of consumers will grow.

Ideally I'd only allow the Gateway to connect to the actual wifi network/internet once a month, for updates, or when installing a new add-on. Then for the rest of the time I'd connect a single tablet to the Gateway while it's hotspot mode, and use that to manage it in situations where voice doesn't suffice (e.g. looking at data logs). 

As a side note, this is a good example of why it would rock if the Pi gateway image would function as a basic hotspot. Sometimes wifi devices can't really be avoided, such as with security cameras. If the Pi could be connected to, it would allow me to connect untrustworthy wifi devices (e.g. security camera) to it instead of my home network.

**Comment by eode** [comment]
I can heartily agree that acting as a hotspot (with the *option* to share the internet with that network) is a pretty solid idea.  It would be nice to just check a box, do your updates for all of your WiFi-connected devices, and then uncheck that box -- and know that your IOT devices are basically invisible to the outside world.

That aside -- I strongly want to retain the ability for this to function in an offline mode.  If I unplug everything and log onto the pi directly for some development work, it should be accessible via 127.0.0.1.

**Comment by benfrancis** [comment]
>  I'd argue that connecting to the network should not be the default.

Just a note to say that this is definitely a bug, the gateway should definitely be able to start up without a network connection. But also to emphasise the main purpose of the WebThings Gateway is to directly monitor and control your home over the _web_. You can't really have the Internet of Things without the Internet.

It has always been a goal of the project that as much as functionality as possible should continue to work when your Internet connection goes down, and that communication should be local by default where possible. But I'm afraid if you're expecting any Internet of Things hub to work completely offline then you're probably going to be disappointed and if you're looking for a completely offline smart home solution then WebThings may not be it.

> I only purchases devices that create their own separate network (zigbee, z-wave, bluetooth, mysensors). IKEA understands this too. In the coming years this group of consumers will grow.

If the [Connected Home over IP](https://www.connectedhomeip.com/) initiative achieves its goals (with "security as a fundamental design tenet") it seems more likely that in the coming years consumer devices (including those using Bluetooth and 802.15.4) will be based on IPv6.

I would argue that IP-based standards are not inherently less secure or private than non-IP technologies, it's how those standards are implemented and used which is important (e.g. communicating locally by default vs. always requiring a round trip through a commercial cloud service and following best practices around encryption and the handling of private data).

**Comment by flatsiedatsie** [comment]
> You can't really have the Internet of Things without the Internet.

Well, is the goal to create connected things or to create 'smart' things? Whether a device actually needs to connect to the internet should in my opinion always be second to the question of whether or not it needs it. Should we connect things for the sake of connecting things? I do think there's room for a critical stance here.

I perceive some politics here too. There's a dire need for a privacy friendly smart home system, but I can imagine that to explain why Mozilla would get involved in this field, there will have to be some kind of "it's about the web" narrative. 

But I wish there didn't have to be. I wish the goal was to create an ethical smart home system that has standardised features instead of a standardised connected smart home system that has ethical features.

Anyway, I get that this is the focus, and I'm not saying that's odd or bad. It's totally logical, and it's already awesome that ethics is on the agenda. I guess I'm just saying that I hope the Gateway will continue doing so well in allowing someone like me to actually use the Gateway to push a narrative that may sometimes seem like its opposite to what the Gateway is trying to achieve. I think the very fact that this is possible speaks to the strength of the project.
 
And since this very issue is about making sure that a network connection is not required for the gateway to start, I don't have any worries about these two use cases both being possible :-)

**Comment by mrstegeman** [comment]
This should be fixed now that the integrated mDNS server has been dropped.

**Comment by mrstegeman** [comment]
See #2495
