### ISSUE TITLE
Replace install instructions with a script or playbook

### ISSUE THREAD

**Issue by ssbarnea** [WebThingsIO/gateway#2345]
There are lots of steps mentioned on https://github.com/mozilla-iot/gateway#install-os for installing and it would be much better to have a single script (or playbook) to install mozilla-iot on a new device.

In addition to the fact that it would make the user experience much better, it would always prevent getting documentation outdated because it could easily be tested on CI.

**Comment by mrstegeman** [comment]
There actually is a barbones installation script here: https://github.com/mozilla-iot/gateway/blob/master/install.sh

We're working on creating installable packages as well, so that people will not have to build the gateway on their own. Currently, we have the following:
* Raspberry Pi image
* Docker image
* AUR package for Arch Linux

We're looking into the following:
* apt package for Debian/Raspbian/Ubuntu
* snap package

If you have expertise in writing playbooks, I'd welcome a PR!
