### ISSUE TITLE
data logging autoscale sometimes odd

### ISSUE THREAD

**Issue by kgiori** [WebThingsIO/gateway#2366]
Input from [MicroBlocks](microblocks.fun) team:

The gateway attempts to auto-scale the data log graphs, but it sometimes does strange things.

Here's one example:
![image](https://user-images.githubusercontent.com/9487286/70744121-f60ed380-1cd5-11ea-8e74-0e1d91cda2a4.png)

One strange thing is that the base and maximum points are fractional numbers but the data are integral values of temperature. It would be nice if the autoscaler code could notice that the data only contained integers and pick integers for the base and max of the graph scale.

The other strange thing is that it didn't set the base value to be the minimum value in the displayed range. As it is, the graph display falls below the base line and overlaps with the scroll bar. (Maybe this would have been fixed with a page reload.)

If more dynamic auto-scaling is not easily accomplished, then there could be a "refresh button" to force re-scaling.

Finally, a feature that would make data logging more useful to science classes would be a way to download the logged data as a CSV file so it could be imported into other programs for analysis.

The graphing is already a terrific feature. Fixing these issues would make it even better!

**Comment by benfrancis** [comment]
@hobinjk Could you hazard a guess as to what's going on here?

In general I don't think we should optimise the core UI for science classes because that's not the intended use case (the intended use case is the smart home). But the ability to export logging data seems broadly useful, so I've filed https://github.com/mozilla-iot/gateway/issues/2375 for that.

It would of course also be possible to build a logging extension add-on which provided a more sophisticated UI for use in the classroom.

**Comment by hobinjk** [comment]
A curs
