### ISSUE TITLE
Make the floorplan bigger / icons smaller

### ISSUE THREAD

**Issue by soulfire03** [WebThingsIO/gateway#2683]
Hello,
I'm trying to make the plan bigger, but no matter how I size the image, it doesn't change in the app.
The elements icons are way too big to fit in there.

Note that I wanted to have the basement floor on the same image, so the rooms ends up being fairly small once uploaded in the app.
I attached the image (not to scale) if you wan't to see how it appears.
![plan maison](https://user-images.githubusercontent.com/39413022/102166361-eaf70200-3e59-11eb-8e5b-6a3f65da8c33.png)

**Comment by benfrancis** [comment]
Hi @soulfire03,

The floorplan view scales the floorplan image to fit inside a square which is stretched as large as possible to fit the screen. This is necessary so that x & y co-ordinates saved in the database for the position of things are consistent across any screen size, ratio and orientation.

The best way to maximise the size of the floorplan is to make the image as square as possible and to fill that square as much as possible with very small borders. Obviously you are constrained by the shape of your house but you could consider changing the orientation of your floorplan floors to make it more square.

Hope this helps

Ben

**Comment by soulfire03** [comment]
Hi Ben, I understand the constraints you have.
Is it possible to add a tabbed control to display different floor levels?

**Comment by benfrancis** [comment]
> In the other hand, I think that even doing this won't be enough to place the enormous devices icons on the plan. Why does it have to be that big?

If you view the floorplan on a mobile device you will see why, the icons become very small. They are rendered that size to ensure a large enough touch target on touch screens and maintain readability. We used to have a separate smaller icon rendering for devices for the floorplan view, but when we made it interactive we wanted to re-use the same web components for devices to capture the full versatility of the thing icons.

However, thank you for highlighting the challenges with larger floorplans. I have filed #2687 to explore UI solutions to this problem.
