### ISSUE TITLE
Add bluetooth config

### ISSUE THREAD

**Issue by soulfire03** [WebThingsIO/gateway#2692]
Hello,
Would it be possible to add a bluetooth config page like the wifi or ethernet page, to be able to connect audio to external speakers?

Plus : Would it be possible to change the paired device with rules?
Let's say I want to connect to this X speaker from 8pm to 5am, then I want to be paired to this Y speaker the rest of the day.

**Comment by mrstegeman** [comment]
@flatsiedatsie proposed an [add-on](https://github.com/WebThingsIO/addon-list/pull/996) for this a while back, but it didn't seem like a great fit as an adapter, and I never got a solid use case for it. You may want to read through the discussion there and see what you think.

**Comment by soulfire03** [comment]
I went through the comments. I somewhat agree that maybe it's not for an addon to do this, but one thing I think it should not happend is to have multiple forks of webthings emerging. I think the product would be stronger if everyone could put their contribution in there, making a very diversified product.

Maybe you could just allow a bluetooth connect in the settings, as for now the only way to play music is through wire and it's not practical for me.

**Comment by flatsiedatsie** [comment]
@soulfire03 Thank you for this :-) 

I personally felt that connecting a bluetooth speaker was a pretty solid use case. 
- I was/am working on multi-room local voice control, for which bluetooth speakers are really really useful. They are cheap, and come with built-in microphones.
- I enjoy streaming audio from my laptop to speakers around the house, and the Airplay addon makes this so easy to do.
- I have a central controller (Raspberry Pi) with a touch screen. Connecting a bluetooth mouse and keyboard would make this a very nice setup.

Even right now I'm testing multi-room voice control, and have to switch the one speaker I have that doesn't auto-shutdown. Most bluetooth speakers can be connected via aux-in, but even when they are continously powered, they turn themselves off if there isn't an incoming audio signal. When they are connected via bluetooth they do stay connected.

I personally feel that the barier for allowing addons should be low. Let users decide what they want to install. The more things the Gateway can do, the more attractive it becomes.

End of rant ;-)

**Comment by benfrancis** [comment]
@soulfire03 wrote:
>  Would it be possible to add a bluetooth config page like the wifi or ethernet page, to be able to connect audio to external speakers?
> Plus : Would it be possible to change the paired device with rules?

Rather than implement this as part of the gateway settings I'd suggest Bluetooth devices in general should really be added as web things using an adapter add-on, particularly if you want those devices to be used as inputs or outputs in the rules engine. Unfortunately as you have seen due to the Bluetooth implementation on Linux this has proved hard to achieve.

> Let's say I want to connect to this X speaker from 8pm to 5am, then I want to be paired to this Y speaker the rest of the day.

That's a bit more tricky. I can imagine rules which play audio on different Bluetooth speakers at different times of day though. What exactly are you trying to achieve?

@flatsiedatsie wrote:
> I have a central controller (Raspberry Pi) with a touch screen. Connecting a bluetooth mouse and keyboard would make this a very nice setup.

I am sympathetic to what you're trying to build because as I've mentioned I am also working on a kiosk runtime to run alongside the gateway on a device which also has a touch screen and audio input/output. But what you are describing here is essentially a desktop computer and the current main WebThings Gateway image (built on Raspberry Pi OS Lite) is intended for use with headless IoT gateways, not desktop computers. If you want to run WebThings Gateway on a desktop computer then I recommend you take another approach (e.g. installing the .deb package on the full desktop version of Raspberry Pi OS.) and use other software packages for managing mice, keyboards and audio input/output etc. I'm still exploring using Ubuntu Core for this, but there's quite a lot of work involved.

The way that we maintain the usability of the gateway software (which you kindly describe as one of its strengths) is precisely by saying _no_ to features which don't fit within the scope of its intended usage model and could therefore confuse users who are using it in the way it is intended.

There is always a tradeoff between UI simplicity and configurability and if you want to customise the gateway software to be used on a completely different hardware form factor than intended then I'm afraid you're going to have to expect to do a bit more work.

I completely recognise the issues you're running into and I'd like to work together on solving them, because I too would like the gateway software to be able to run on devices which can also act as a touch/voice controller. I just think it's too much to ask of the main gateway software image, which is designed to run on headless IoT gateways. We had similar issues when we tried to make the UI flexible enough to run on both IoT gateways (as a Wi-Fi client) and wireless routers (as a Wi-Fi access point). In the end in order to keep the network settings and first time setup UI simple we had to create two separate distributions of the software with different versions of the user interface for those different use cases.

**Comment by soulfire03** [comment]
I'm not trying to do voice recognition or touchscreen input. My Pi will stay in the network rack without triggering human interaction. 
What I am trying to do is to start audio playback of a relaxing music on the children rooms at night, which would start automatically at a given time, and stops by itself.
Then I would like to start internet radio automatically (using the existing webthing) in the kitchen on the morning at a given time.

So it would basically stay a headless system

**Comment by soulfire03** [comment]
On the other hand, my speakers can be controlled by Wifi too, so when the team have time it would be nice to have an add-on for these speakers. They are Samsung M7, but basically the smaller M3 and M5 of the serie should work too.

**Comment by benfrancis** [comment]
> Every other hub like Alexa or Google home are able to do this

WebThings Gateway is not comparable to the software running on Amazon Echo or Google Nest devices (which with a couple of exceptions are are speakers/microphones acting as thin clients to a cloud service, not hubs), it is more comparable to the software which runs on a SmartThings or Wink hub.

> Maybe this could be achieved using one RPi for each speaker (wired audio instead of bluetooth), and sending a request to them to start/stop playback.

Using a Raspberry Pi for each speaker could work, but I'd maybe suggest using a media streaming protocol over Wi-Fi rather than an analogue audio cable. I don't know if anyone has achieved this kind of media playback use case on a Raspberry Pi yet, but it would be an interesting project and we're working on a [MediaPlayer](https://github.com/WebThingsIO/schemas/issues/34) capability which might help.

If you were so inclined you might be able to use an Amazon Echo or Google Nest device for this, there's an existing Chromecast add-on but it might not quite be able to do what you need due to restrictions on the Google Cast API. There also add-ons that I haven't personally tried like the Sonos add-on which might be able to do something like this.

**Comment by kgiori** [comment]
More food for thought.

I set up a (temporary) WebThings Gateway for my smart xmas tree, colocated with the tree so I could connect smart ornaments to it (over USB) and control when they go on/off, plus what patterns to show and when to play little holiday music ditties with dancing LEDs. I installed the Internet Radio add-on, and configured it to point to a holiday music station. I had to use a direct audio cable to connect to a speaker, even though that speaker also supported Bluetooth, which meant I had to locate the speaker under the tree too. However, I ran into the same "speaker goes to sleep" problem as @flatsiedatsie. Therefore, even ignoring rules/schedules, I couldn't just turn on music from the web UI without physically going over to the powered speaker and waking it up (thereby losing the convenience factor). A low-tech pair of PC speakers connected over audio cable overcame that problem but the sound was terrible. For my main smart home gateway I use a Sonos speaker (connected to the network over Ethernet). The Sonos add-on works great, but that was in a different area of the house and associated with a different WebThings gateway. 

If it is deemed that it is better to keep Bluetooth config outside the core gateway software, then would an extension add-on approach work better than a regular add-on? I recently installed the "Followers" extension add-on so that my smart ornaments all follow the same pattern number as the first one, and it works great (so much better than having to create tons of rules). I don't know what the Bluetooth config UI should be, so @soulfire03 and @flatsiedatsie are in a better position to suggest options, and whether an extension add-on or regular add-on would work better.

It also occurred to me that my smart watch uses Bluetooth (and has an API), and that my electric car has Bluetooth. Even without "data transfer" use cases that could be interesting in the future, I can imagine "presence" as a useful use case. When my car comes or is home, do or don't do x. When my watch is home, or perhaps in a specific room, do or don't do y. Etc. 

And lastly, there could be health and fitness use cases. I just thought of a safety use case. My mom told me that her smart watch can detect if she falls. Even a simple BBC micro:bit has a built-in accelerometer that could be configured to detect a fall, and if detected, send an event to a local gateway. I think that a lot of medical and fitness devices use low-power BLE these days.

Actually one more thought, might there be use cases for wireless BLE ear buds?

**Comment by flatsiedatsie** [comment]
The bluetooth addon I created was originally had a narrow goal. It was supposed to connect bluetooth speakers, so that it was easier to create cheap satellites for voice control.

All I wanted was to be able to put a Pi Zero W somewhere in my kitchen, and use a UI to connect it to a bluetooth speaker and microphone combo device, which I would then place on the kitchen counter. That way I wouldn't have to shout into my livingroom everytime I set a cooking timer using Voco.

> WebThings Gateway is not comparable to the software running on Amazon Echo or Google Nest devices

Why not? Voice control seems to be part of the WebThings Gateway usecase, since the team has itself been working on implementing this. Having voice control means having a speaker and microphone attached. Having the ability to connect bluetooth speakers would, in my eyes, support this use case. And once you have a speaker attached, it's not strange for users to think "hey, I'd love to also play some music through my investment".

> ... could therefore confuse users who are using it in the way it is intended.

If you mean that addons should focus on a specific type of devices, then I'm all for that. We could make a "bluetooth speaker" addon and a "bluetooth mouse and keyboard" addon.

Like it or not, the WebThings Gateway users see it as a smart home controller that can compete with things like Domoticz and Home Assistant, and yes, even Amazon Echo. It's a platform, so you'll always run into users wanting to use it as, well, a platform.

**Comment by kgiori** [comment]
Interesting bluetooth use cases discussion. And by the way, I love using private local voice with the gateway and I'm not alone. Whenever I do demonstrations or give workshops, having local voice control is the jaw-dropping feature that attracts the most questions. 

But back to bluetooth. I have a portable, battery-operated bluetooth speaker and it would be great to be able to put it wherever I happen to be, and play music. Even without voice/mic control of the speaker, it'd be a nice thing to have. 

Would bluetooth "pairing" be vendor specific? I don't have a good sense for whether bluetooth pairing/settings should be generic to the gateway or device-type-centric or vendor-product-centric or ... but because it is significantly lower power than Wi-Fi, I'd like to see the gateway support bluetooth devices. (I also still like my bluetooth device "presence" idea for an add-on too.)

**Comment by flatsiedatsie** [comment]
@kgiori Pairing bluetooth speakers would not be vendor specific.

**Comment by kgiori** [comment]
I would happily give music-streaming-over-bluetooth a try.

**Comment by madb1lly** [comment]
Hi @kgiori,

@flatsiedatsie is right, some classes of BT device like speakers, headsets, keyboards, mice, should all use a standard profile which is vendor-independent. Other devices use profiles which permit the vendor flexibility with implementation, AFAIK, especially BLE devices like environmental sensors, in which case they will need device-specific add-ons to be developed, OR a generic addon which can have profiles loaded into it (I quite like this idea).

If the gateway could support standard OEM-independent BT device profiles, either natively or via an addon, that would be a great enhancement. Personally I would find microphones and speakers most useful for voice control and audio feedback. To me the WebThings Gateway certainly feels like a smart-home control hub, and smart speakers have become very closely associated with that idea. If the gateway is not meant to be a smart-home hub then I'm a bit confused about its identity.

However, isn't there still this underlying problem that only one addon can control the BT interface at a time? I think there's little point expanding BT addon capabilities before that is addressed.

Cheers :)

**Comment by flatsiedatsie** [comment]
If you are running the Raspberry Pi image, you can try the bluetooth addon I created by running this command in the `SeaShell` addon:

`git clone https://github.com/flatsiedatsie/bluetoothpairing /home/pi/.webthings/addons/`

After that you'll have to reboot, and then it will show up as an installed addon.

In theory you could then pair generic bluetooth devices. I haven't been able to test it because I don't own a bluetooth keyboard or mouse.

It's not able to connect bluetooth speakers because some additional software is needed that isn't installed by default (ALSA bluetooth support). My hope was that the Raspberry Pi image would come with that pre-installed (it's a few kilobytes).

![bluetooth_pairing](https://user-images.githubusercontent.com/805405/105682219-769c8d80-5ef2-11eb-8e44-f6d50971cff8.png)

**Comment by benfrancis** [comment]
Going back to the original use case...

@soulfire03 wrote:
>I'm not trying to do voice recognition or touchscreen input. My Pi will stay in the network rack without being triggered by human interaction.
> What I am trying to do is to start audio playback of a relaxing music on the children rooms at night, which would start automatically at a given time, and stops by itself.

Written as a user story:
"As a user I want to tell a device to play back audio as the output of a rule, so that I can play relaxing music for my children at a particular time."

One way to achieve this (as discussed above) is to create a custom native web thing, e.g. with a Raspberry Pi + speakers. But I wonder if there's another way to achieve this which could use off-the-shelf Bluetooth hardware, but without compromising the user interaction model.

@mrstegeman wrote:
> @flatsiedatsie proposed an add-on for this a while back, but it didn't seem like a great fit as an adapter, and I never got a solid use case for it.

As I understand it the add-on that @flatsiedatsie created was an extension add-on which provided UI for pairing Bluetooth devices (intended to be used via a touch screen directly attached to the gateway), not an adapter add-on which exposes Bluetooth devices as web things. It therefore wouldn't be possible to use the device as the output of a rule.

What if we created a Bluetooth adapter add-on which exposed various [standard Bluetooth profiles](https://en.wikipedia.org/wiki/List_of_Bluetooth_profiles) as web things? For example, a Bluetooth speaker could be added as a web thing with a `play` action which accepts an audio file/stream as an input.

I've filed https://github.com/WebThingsIO/addon-list/issues/1256 to discuss this further and will therefore close this issue as I think that approach makes more sense than adding something to the Settings UI.

The discussion about the best architectural approach to use the gateway software package as part of a smart speaker/smart display product is a separate topic which I'm happy to discuss elsewhere. But in summary, the main gateway distribution based on Raspberry Pi OS Lite is designed for headless smart home hub hardware without video or audio input/output (think SmartThings or Wink hub type hardware). I'm happy to discuss working on a separate distribution of the gateway software which targets smart speakers and smart displays and has a user experience optimised for those form factors (e.g. with a different first time setup UI, audio/display settings etc.).
