### ISSUE TITLE
Additional default packages for Raspberry Pi

### ISSUE THREAD

**Issue by flatsiedatsie** [WebThingsIO/gateway#2795]
I'd like to suggest a few packages that would be really great to have installed on the Rasbperry Pi image by default.

- Alsa Bluetooth. If connecting bluetooth speakers is something to be explored, then this would be vital. From what I remember it's about 17kb :-)
- GPIO Zero? Perhaps there is already a default python library to access the GPIO on the Raspberry Pi. If not, let's pick one? GPIO Zero is the default package on Raspbian for desktop, but it's not installed on the Lite image. Installing it: `sudo apt install python3-gpiozero`

**Comment by kgiori** [comment]
Since the image for RPi is already custom, I like the idea of adding useful packages to it.

* ALSA Bluetooth. Thumbs up from me to be able to test streaming to a bluetooth speaker. (e.g., using the Internet Radio add-on.)

* GPIO Zero. There is already a vanilla "GPIO" add-on, that I have successfully used. It lets you generically control pins on the Pi header. But I like the idea of leveraging GPIO Zero if it is what RPi users are already familiar with. Also, if GPIO Zero supports pre-canned definitions or configurations or whatever is needed to talk to a variety of commercial RPi HATs (epaper, environment HAT, the Pimoroni Blinkt! RGB strip that I have, ANAVI HATs, etc.), so that I don't have to figure them all out, that would be super useful. I have used the Pimoroni Blinkt! Add-on and it works great. But seems even better if a more generic add-on could let you select from a list of popular Pi-HATs or configure the GPIOs manually. Rather than guess, I should go look at it... :)

**Comment by mrstegeman** [comment]
I'd be ok with adding the ALSA bluetooth package, as that makes sense.

GPIO Zero, though, not so much. It's just a Python package, which can easily be pulled in by an add-on and can be more easily pinned to a specific version that way.

**Comment by flatsiedatsie** [comment]
> I'd be ok with adding the ALSA bluetooth package, as that makes sense.

Great!

> GPIO Zero, though, not so much. It's just a Python package, which can easily be pulled in by an add-on and can be more easily pinned to a specific version that way.

Indeed, I tested it an the GPIOzero python package could be loaded fine. I was worried it required some low-level drivers, but it doesn't.

Another suggestion, which I'm uncertain about, is adding built-in support for ReSpeaker Pi Hats. Enabling it is likely to change some lower level things. For example, here's the list of files it removes when it uninstalls:

```
echo -e "\n### Remove seeed-voicecard"
rm -v /usr/bin/seeed-voicecard || true
rm -v /lib/systemd/system/seeed-voicecard.service || true

echo -e "\n### Remove dkms"
rm -rfv /var/lib/dkms/seeed-voicecard || true

echo -e "\n### Unload codec driver by modprobe -r"
modprobe -r snd_soc_ac108
modprobe -r snd_soc_wm8960
modprobe -r snd_soc_seeed_voicecard

echo -e "\n### Remove kernel modules"
rm -v /lib/modules/*/kernel/sound/soc/codecs/snd-soc-wm8960.ko || true
rm -v /lib/modules/*/kernel/sound/soc/codecs/snd-soc-ac108.ko || true
rm -v /lib/modules/*/kernel/sound/soc/bcm/snd-soc-seeed-voicecard.ko || true
rm -v /lib/modules/*/updates/dkms/snd-soc-wm8960.ko || true
rm -v /lib/modules/*/updates/dkms/snd-soc-ac108.ko || true
rm -v /lib/modules/*/updates/dkms/snd-soc-seeed-voicecard.ko || true
``` 

So far having this installed ([github](https://github.com/respeaker/seeed-voicecard)) doesn't seem to affect things like Voco, which work just fine. In this case I'm using the [ReSpeaker 2 mic hat](https://wiki.seeedstudio.com/ReSpeaker_2_Mics_Pi_HAT/), which is wonderfully cheap and fits on both the Pi zero and normal Raspberry Pi's.

**Comment by benfrancis** [comment]
@mrstegeman wrote:
> I'd be ok with adding the ALSA bluetooth package, as that makes sense.

I agree, if there's a genuine use case for creating an adapter add-on which exposes Bluetooth speakers as web things, a package like ALSA bluetooth would make sense.

@flatsiedatsie wrote:
> Another suggestion, which I'm uncertain about, is adding built-in support for ReSpeaker Pi Hats.

As explained before, the default Raspberry Pi image of WebThings Gateway (built on Raspberry Pi OS Lite), is designed for headless (i.e. no screen, touch panel, microphone or speaker) smart home hubs. I have recently received feedback from hardware vendors that the software is already too bloated for their production hardware. Adding additional packages which those devices don't need is only going to make that situation worse, and increase the maintenance burden (which is going to become a serious problem soon, when we have to upgrade to a newer version of Raspberry Pi OS).

Rather than try to augment the existing OS image into a distribution for smart speakers and smart displays via add-ons and additional dependencies, my suggestion is to create a separate distribution specifically for those devices. It's quite common for Linux distributions to have separate desktop and headless versions (e.g. Raspberry Pi OS & Raspberry Pi OS Lite, Ubuntu Desktop & Ubuntu Server etc.) so this makes perfect sense to me.

I have created a [controller](https://github.com/WebThingsIO/controller/) for work on controller software and filed #2796 to discuss a separate distribution for smart speakers & smart displays. The challenge we're going to have is finding the resources to maintain it.

@flatsiedatsie There's always the option of you creating a downstream distribution (e.g. "Candle OS") which bundles the WebThings Gateway application alongside your choice of additional software packages (I am considering the idea of doing something similar for enterprise gateways). You could then host your own OTA update servers and add-ons directory to have complete freedom and control over what software is included.

**Comment by mrstegeman** [comment]
@flatsiedatsie what’s the actual name of the ALSA Bluetooth package?

**Comment by flatsiedatsie** [comment]
> I have recently received feedback from hardware vendors that the software is already too bloated for their production hardware. Adding additional packages which those devices don't need is only going to make that situation worse

I thought as much. I agree and rest my case.

I understand about creating `Candle OS`, but if possible I'd like to conserve energy as much as possible and keep things in one project. It would be a last resort, something I'd only do if things get to a "create a real product" stage.

**Comment by flatsiedatsie** [comment]
I went over my notes from trying to create a bluetooth speaker addon, and I think what I ran into back then was that A2DP wasn't enabled. I was able to connect a speaker, but no sound came out. 

From my notes, it might be that it's as simple as adding `--plugin=a2dp` to the service file for Bluetooth:

```
ExecStart=/usr/lib/bluetooth/bluetoothd --plugin=a2dp
```
From https://gist.github.com/actuino/9548329d1bba6663a63886067af5e4cb , but there is also installs pulseaudio first, so I'm not sure if this is a 100% solution. When researching this I found that most tutorials relied on Pulse Audio, which I didn't want to rely on (for those bloat reasons).

I also found this in my notes: https://github.com/Arkq/bluez-alsa

And this: https://gist.github.com/actuino/9548329d1bba6663a63886067af5e4cb#gistcomment-3511713

I could do some experiments to see what the minimal thing needed for Alsa is if you'd like?

**Comment by flatsiedatsie** [comment]
```
pi@grunt:~ $ sudo apt install bluealsa
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libsbc1
The following NEW packages will be installed:
  bluealsa libsbc1
0 upgraded, 2 newly installed, 0 to remove and 73 not upgraded.
Need to get 88.3 kB of archives.
After this operation, 327 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
```

**Comment by flatsiedatsie** [comment]
A small update on the GPIO proposal: it [turns out](https://www.raspberrypi.org/forums/viewtopic.php?p=273886) that `gpiozero` and similar pure python GPIO libraries aren't able to address the pi's hardware PWM. I'm coïncidentally running into that limitation now as I'm trying to run a servo from the pins. The servo is jittering like crazy.

Gpiozero can fall back on two libraries that do offer this ability.
- rpio can do it. It needs to be run as root. It's ancient, and only works on the Pi1, so not really relevant.
- pigpio can do it on all pi models. uses a daemon that needs to be used as root.
 
Wiringpi can also manage the hardware PWM. It also needs to be run as root to manage the hardware.

I found this blogpost from someone looking at this a week ago, who mentioned another approach: a "DTS Overlay". https://github.com/scottellis/pwmpy

I then wondered if NodeJS is able to address the hardware more thoroughly than Python, but that doesn't seem to be the case.

If allowing hardware PWM is relevant enough, then `pigpio` seems to be a solution that has both Python and Nodejs support.

**Comment by flatsiedatsie** [comment]
The pigpio deamon seems to take about a megabyte of space.

```
sudo apt-get install pigpio 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libpigpio-dev libpigpio1 libpigpiod-if-dev libpigpiod-if1 libpigpiod-if2-1 pigpio-tools pigpiod
The following NEW packages will be installed:
  libpigpio-dev libpigpio1 libpigpiod-if-dev libpigpiod-if1 libpigpiod-if2-1 pigpio pigpio-tools pigpiod
0 upgraded, 8 newly installed, 0 to remove and 36 not upgraded.
Need to get 332 kB of archives.
After this operation, 1008 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
```

**Comment by flatsiedatsie** [comment]
It seems there is a command line program installed called 'gpio'. Perhaps it can already to PWM. Then nodeJS and Python programs could in theory call that program to do hardware PWM.

**Comment by benfrancis** [comment]
@flatsiedatsie wrote:
> it turns out that gpiozero and similar pure python GPIO libraries aren't able to address the pi's hardware PWM.

I have never come across IoT gateway hardware which includes a servo. Why do you need to connect a servo directly to GPIO pins on your IoT gateway? Is your personal use case so compelling that all users of WebThings Gateway should have to have extra software pre-installed in order to facilitate it? Have you considered building a custom web thing using the WebThings Framework instead?

As an aside, [this Python library](https://pypi.org/project/RPi.GPIO/) provides software-based PWM for Raspberry Pi, but if you really want to drive a servo from a Pi I'd recommend using a HAT with a microcontroller on it like [RoboHAT](https://shop.4tronix.co.uk/products/robohat). I've used that myself to drive a servo from a Raspberry Pi-based web thing using the webthing-python library. (See [robohat.py](http://4tronix.co.uk/robohat/robohat.py) for an example of PWM configuration).

**Comment by flatsiedatsie** [comment]
>  Is your personal use case so compelling that all users of WebThings Gateway should have to have extra software pre-installed in order to facilitate it?

My personal use case probably not, and I completely understand where you're coming from. But I wouldn't want to asume that nobody has a valid use case for accurate PWM, simply because I can't imagine it?

> Have you considered building a custom web thing using the WebThings Framework instead?

I have. Spent a lot of time on that. Didn't work :-(

>  using a HAT with a microcontroller on it like RoboHAT

That's a solid suggestion, but for my use case, where space is at a premium, it's not really an option.

It's all moot, since WiringPi is already installed.

**Comment by kgiori** [comment]
One of my colleagues, Bernat, recently updated [MicroBlocks](http://microblocks.fun) support for RPi devices (the VM app running on the RPi is called GnuBlocks-Pi). It's still experimental and in development, but MicroBlocks supports both a WebThing library and a Servo library, and it is really intuitive to use, being a live programming environment. Might not be your choice for a commercial product, but for prototyping and experimenting it's amazing. I'm happy to put you in email contact with Bernat if you're interested in exploring this option. Otherwise one of these days I'll try to find time to experiment myself.

**Comment by flatsiedatsie** [comment]
It's not really an option for the project I'm working on, but great news none the less @kgiori

**Comment by flatsiedatsie** [comment]
Another suggestion just to test the waters: it seems `U4VL` is a raspberry pi project that is geared towards live video stream, and two-way video communication. Could potentially be great basis for adding real-time bi-directional video+audio support? ? E.g. doorbells and baby monitors?

https://www.linux-projects.org/uv4l/
