### ISSUE TITLE
Websocket connection getting closed

### ISSUE THREAD

**Issue by atirage** [WebThingsIO/gateway#2915]
I'm trying to open a websocket connection to one of my things running on the gateway, but the connection is closed right after it's established.
I'm using the websocket-client python module, but I tried a websocket Firefox extension as well, see below:
![Screenshot at 2022-02-09 22-08-20](https://user-images.githubusercontent.com/2630602/153290400-176de666-9c80-409b-b28e-ef5b3f32985b.png)

Using the python module, I'm able to open a websocket to a standalone Webthing.

Can anyone give me some hints on this?
Thanks in advance!

**Comment by benfrancis** [comment]
Because WebSocket connections don't support Authorization headers, you need to add a JSON Web token to the URL in order to authorise the request. I'm guessing that's your problem. Try...

ws://gateway.local/things/zb-84fd27fffe1f812e?jwt=[token]

where [token] is your JWT. You can generate one in developer settings, or look for the WebSocket connection in the network console of your browser when using the gateway's web interface and copy the token from there.

**Comment by atirage** [comment]
Thanks, @benfrancis! That was it, connection is up and running.
